[bumpver]
current_version = "0.4.2"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
tag = true
push = false
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "global"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"'
]
"spotifysaver/__init__.py" = [
    '__version__ = "{version}"'
]