name: 🐛 Bug report
description: Report a bug you've found
title: "[BUG] Brief description of the error"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve the app. Please complete the following information.

  - type: input
    id: context
    attributes:
      label: Context
      description: Where did the error occur? What were you doing?
      placeholder: "For example, when downloading an album in the CLI..."

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the error
      description: Describe the steps so we can replicate it
      placeholder: |
        1. Go to...
        2. Click on...
        3. View the error...

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What should have happened?
      placeholder: "The system should have..."

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Screenshots, logs, etc.