name: Functionality request
type: issue
description: Suggest an improvement or new feature
title: "[FEAT] Brief description of functionality"
milestone: ''
labels: enhancement
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your proposal! Tell us more about the functionality you envision.

  - type: input
    id: resumen
    attributes:
      label: Summary
      description: What functionality do you propose?
      placeholder: "e.g., Add multiple download sources..."

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: Do you have any idea how it could be done?
      placeholder: "A button could be added to..."

  - type: textarea
    id: considerations
    attributes:
      label: Additional considerations
      description: Risks, dependencies, etc.