from spotifysaver.services.schemas.track_audiodb_schema import TrackADBResponse
from spotifysaver.services.schemas.album_audiodb_schema import AlbumADBResponse, MediaAlbumURLs, AlbumDescription
from spotifysaver.services.schemas.artist_audiodb_schema import ArtistADBResponse, ArtistBiography, ArtistFanart, MediaArtistURLs
